### ISSUE TITLE
Consts issue

### ISSUE THREAD

**Issue by luciocc55** [sushiswap/sushiswap-subgraph#84]
Hey guys im trying to try the build for your project and its throwing an error, not really sure what i should do, im running exchange,maker and masterchef subgraphs everything else is the same as the current branch. thanks in advance

Compile data source: Factory => build/Factory/Factory.wasm
✖ Failed to compile subgraph: Failed to compile data source mapping: Import file '~lib/const.ts' not found.
Error: Failed to compile data source mapping: Import file '~lib/const.ts' not found.
    at Compiler._compileDataSourceMapping (/home/ares/blockchain/sushiswap-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler.js:314:13)
    at /home/ares/blockchain/sushiswap-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler.js:207:20
    at updateInDeepMap (/home/ares/blockchain/sushiswap-subgraph/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/home/ares/blockchain/sushiswap-subgraph/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/home/ares/blockchain/sushiswap-subgraph/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/home/ares/blockchain/sushiswap-subgraph/node_modules/immutable/dist/immutable.js:1278:26)
    at /home/ares/blockchain/sushiswap-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler.js:206:24
    at /home/ares/blockchain/sushiswap-subgraph/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/home/ares/blockchain/sushiswap-subgraph/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/home/ares/blockchain/sushiswap-subgraph/node_modules/immutable/dist/immutable.js:3015:23)

**Comment by luciocc55** [comment]
had to run yarn alone in the project to make it work

**Comment by DramaCrypto** [comment]
Hi @luciocc55 
I have same issue in my side as well.
Sorry, but can you please explain how I can solve this issue?
